apiVersion: v1
kind: ServiceAccount
metadata:
  name: attacker-sa
  namespace: attacker
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: attacker-least-priv-role
  namespace: attacker
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: attacker-least-priv-binding
  namespace: attacker
subjects:
  - kind: ServiceAccount
    name: attacker-sa
    namespace: attacker
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: attacker-least-priv-role
---
apiVersion: v1
kind: Pod
metadata:
  name: attacker-pod
  namespace: attacker
spec:
  serviceAccountName: attacker-sa
  automountServiceAccountToken: false
  containers:
    - name: attacker
      image: bitnami/kubectl:latest
      command: ["/bin/sh", "-c", "sleep 3600"]