apiVersion: v1
kind: Pod
metadata:
  name: attacker-pod
  namespace: attacker
spec:
  serviceAccountName: attacker-sa
  automountServiceAccountToken: false
  containers:
  - name: attacker
    image: bitnami/kubectl
    command: ["sleep", "3600"]