apiVersion: v1
kind: Pod
metadata:
  name: privileged-pod
  namespace: attacker
spec:
  containers:
  - name: attacker
    image: ubuntu
    command: ["sleep", "3600"]
    securityContext:
      privileged: true