apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: chain2-phase1-limited-allow
  namespace: victim
spec:
  podSelector:
    matchLabels:
      app: nginx
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: attacker
      ports:
        - protocol: TCP
          port: 80