apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2026-03-07T23:14:21Z"
  labels:
    app: nginx
  name: nginx
  namespace: victim
  resourceVersion: "506114"
  uid: 249834e0-a043-4c0b-9cfa-bfbb626a61ba
spec:
  clusterIP: 10.103.250.84
  clusterIPs:
  - 10.103.250.84
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
